Added cables
myst-6/ukoly pull request #37
Opened 2024-08-26 18:45 UTC by macaquedev

2024-08-26 18:58 UTC, myst-6 requested changes
missing code

2024-08-26 18:58 UTC, myst-6 commented on solutions/bio2/Cables/index.tsx
> +      <SCodeBlock path="cables/sol" />
The solution isn't showing up on the preview, did you forget to add it?

2024-08-26 21:24 UTC, macaquedev commented
@myst-6 please accept now

2024-08-26 23:54 UTC, myst-6 approved these changes
had to fix merge conflicts so, please blindly accept or double-check this @AG-88301 🙂

2024-08-27 06:48 UTC, AG-88301 approved these changes
works fine

2024-08-27 06:48 UTC, merged