Added BIO2021Q3
myst-6/ukoly pull request #51
Opened 2024-08-27 17:21 UTC by macaquedev

2024-08-27 23:31 UTC, myst-6 requested changes
editorial is all good but just the metadata is slightly wrong

2024-08-27 23:31 UTC, myst-6 commented on content/problems/bio1/index.tsx
> +    original: "https://www.olympiad.org.uk/papers/2023/bio/bio23-exam.pdf",
this link is wrong

2024-08-28 13:33 UTC, macaquedev commented on content/problems/bio1/index.tsx
> +    original: "https://www.olympiad.org.uk/papers/2023/bio/bio23-exam.pdf",
derp

2024-08-28 13:38 UTC, AG-88301 submitted a review, later dismissed
You forgot to remove Vlad's code for dreaming spires

2024-08-28 13:46 UTC, AG-88301 approved these changes
good

2024-08-28 13:46 UTC, AG-88301 commented on solutions/bio1/WindowDressing/index.tsx
> +      <SCodeBlock path="dreamingspires/sol" />
Kill this

2024-08-28 13:46 UTC, AG-88301 commented on solutions/bio1/WindowDressing/index.tsx
> +      <SCodeBlock path="dreamingspires/sol" />
(Line 40)

2024-08-28 13:47 UTC, merged