Parking
myst-6/ukoly pull request #72
Opened 2024-08-30 12:06 UTC by yud08

2022 Q3
Understandable or nah

2024-08-30 12:31 UTC, myst-6 commented on solutions/bio1/Parking/index.tsx
> +import { Link, SCodeBlock, SList, SCode, SText, STitle } from "components";
build fails because "Link" is imported but never used

2024-08-30 14:53 UTC, macaquedev requested changes
Lots of issues, sorry.

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        Clearly, constructing all possible preference lists, then sorting them to find the ith one is much too slow, so you need to find a way to construct the solution letter by letter.
ith should be `$i$-th.`

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        You do this by iterating through each car (a to z), and figuring out which preference spot to give each car so that the final list is the $k-th$ lexographically, while still maintaining a val
`$k$-th` not `$k-th$`
Also, it's spelt lexicographically not lexographically!!

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        You do this by iterating through each car (a to z), and figuring out which preference spot to give each car so that the final list is the $k-th$ lexographically, while still maintaining a val
use latex - `$a$ to $z$`

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        On the other hand, if we have an arrangement like a.bc., and the next arrangement as a.bcd, D can only go in slots C, D, and E. Even though slot A is filled, there is an empty slot in between
I won't tell you every single mistake you've made, but all the ABCD's should have latex on them

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        We want the kth preference list, so we should first keep a counter <SCode>curr</SCode> as we iterate through all the cars, and then iterate in alphabetical order through these slots, and see
`$k$-th`

2024-08-30 14:58 UTC, macaquedev commented on solutions/bio1/Parking/index.tsx
> +        If that number added to <SCode>curr</SCode> is greater or equal to $k$, then we have the correct preference and we continue to the next car; otherwise, we add that to <SCode>curr</SCode>, and
exactly `$1$`

2024-08-30 14:59 UTC, macaquedev commented
Also, @yud08 please insert this in sol.py, in the same directory as sol.cpp

```
from string import ascii_uppercase, ascii_lowercase
from collections import defaultdict
from functools import reduce
from operator import mul


def product(x):
    try:
        return reduce(mul, x)
    except TypeError:
        return 1

if __name__ == "__main__":
    letters = input("Please enter lowercase letters and an integer: ").strip().split()
    letters, n = letters[0], int(letters[1])
    num_cars = len(letters)
    preference_lists = []

    currently_parked = [False] * num_cars
    for current_car in range(num_cars):
        car_symbol = ascii_lowercase[current_car]

        if not any(currently_parked):
            preference_lists.append([ascii_uppercase[letters.index(car_symbol)]])
        else:
            preference_lists.append([])
            for i in range(letters.index(car_symbol), -1, -1):
                if not currently_parked[i] and i != letters.index(car_symbol):
                    break
                preference_lists[-1].append(ascii_uppercase[i])
            preference_lists[-1].reverse()
        currently_parked[letters.index(car_symbol)] = True

    solution = ""
    x = 0
    for i in range(num_cars):
        current_index = -1
        while n > 0:
            x = product([len(i) for i in preference_lists[i + 1:]])
            n -= x
            current_index += 1
        n += x
        solution += preference_lists[i][current_index]

    print(solution)
```

2024-08-30 19:55 UTC, yud08 reviewed
d

2024-08-30 21:01 UTC, macaquedev requested changes
You have fixed precisely *none* of my comments. Are you sure you didn't forget to push or something?

2024-08-31 10:52 UTC, yud08 commented
mb i forgot to add the index file when i committed

2024-08-31 12:36 UTC, myst-6 commented
if you're using the CLI, you can write `git add .` to add all files instead of adding them one by one

2024-08-31 20:29 UTC, macaquedev approved these changes

2024-08-31 20:29 UTC, merged