Bio1 2014 q3
myst-6/ukoly pull request #82
Opened 2024-08-31 17:01 UTC by AG-88301

2024-08-31 18:02 UTC, myst-6 requested changes
hi

2024-08-31 18:02 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        Otherwise, we can recursively call the function with the length $n-1$ and the character $c+i$ for all values of $i$ such that $c+i \leq 36$ (1-indexed).
a bit pedantic but since there are other errors you might as well fix this too

write 'positive integer values of `$i$`'

2024-08-31 18:11 UTC, macaquedev commented on content/problems/bio1/index.tsx
> +    original: "https://olympiad.org.uk/papers/2014/bio/bio-14-exam.pdf",
https://olympiad.org.uk/papers/2014/bio/bio14-exam.pdf

I think GPT generated him that link... 🤡

2024-08-31 18:13 UTC, AG-88301 commented on content/problems/bio1/index.tsx
> +    original: "https://olympiad.org.uk/papers/2014/bio/bio-14-exam.pdf",
no i copied the 2010 stuff from the problem above and changed it... i didnt realise 2010 was special...
also for the record i dont use gpt for much... i sometimes use the copilot autocomplete thing if it seems reasonable

2024-08-31 18:15 UTC, myst-6 commented
I need a second opinion on how the section about building the answer is phrased.  @macaquedev do you think it's clear enough?

2024-08-31 18:22 UTC, macaquedev commented on content/problems/bio1/index.tsx
> +    original: "https://olympiad.org.uk/papers/2014/bio/bio-14-exam.pdf",
I use "GPT" and "copilot" interchangeably, because they're both "gpt"s

2024-08-31 18:23 UTC, macaquedev requested changes
I don't think so.

2024-08-31 18:29 UTC, AG-88301 commented
The last paragraph right @macaquedev @myst-6

2024-09-01 10:17 UTC, myst-6 requested changes
I think the explanation in the last paragraph is good now.

2024-09-01 10:17 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        The number of ways to generate a password of length 1 with all characters greater than $c$: $36 - c$.
`$1$`

2024-09-01 10:17 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        To recursively build the password, we can iterate through each possible character, and check if the number of ways to build it and all the passwords before it is greater than $n$
'greater than or equal to', or 'at least'

2024-09-01 10:17 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        If it is greater, we know that the current letter is the next letter in the result, and so we can append it, and recursively solve for $length - 1$.
'greater than or equal to', or 'at least'

2024-09-01 10:17 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        (it may be useful to think of this like binary/tenary search, with more intervals).
hmmm, I don't know if this sentence is needed, I think it makes it more confusing

2024-09-01 10:19 UTC, myst-6 commented
please also fix the merge conflicts before I re-review :)

2024-09-01 13:01 UTC, myst-6 requested changes
jambloat 😭

2024-09-01 13:01 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        To recursively build the password, we can iterate through each possible character, and check if the number of ways to build it and all the passwords before it is greater than or equal to $n$
you accidentally removed the full stop 😭 
![image](https://github.com/user-attachments/assets/588026b2-4359-4f30-a246-3335c417e44f)

2024-09-01 13:02 UTC, myst-6 requested changes
jambloat 😭

2024-09-01 13:05 UTC, myst-6 requested changes
1more thing

2024-09-01 13:05 UTC, myst-6 commented on solutions/bio1/IncreasingPasswords/index.tsx
> +        We can first set up a base case, where the length of the password is $1$. The output here should be the $n - ways$-th letter possible ($1$-indexed).
oops I missed this earlier

please put (n-ways) in brackets

2024-09-01 13:13 UTC, myst-6 approved these changes
it's over!

2024-09-01 13:23 UTC, merged